name: .NET-Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET v5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/WebApp.sln
    - name: Build
      run: dotnet build --no-restore ./src/WebApp.sln
#    - name: Install dotnet ef
#      run: dotnet tool install --global dotnet-ef
#    - name: Create new migrations
# https://stackoverflow.com/questions/59234655/apply-ef-migrations-in-github-workflow/59344051#59344051
#     - name: Update database
#       run: |
#             dotnet tool install --global dotnet-ef
#             dotnet tool restore
#             dotnet ef database update -p ./src/WebApp/WebApp.csproj
# #            #dotnet ef database update -c ApplicationDbContext -s ./src/WebApp.sln --msbuildprojectextensionspath obj/local
#       env:
#         ASPNETCORE_ENVIRONMENT: Development
## https://stackoverflow.com/a/66324027/14036841
## dotnet ef migrations add NewMigration --msbuildprojectextensionspath obj/local
#      run: dotnet ef migrations add "CreatedNewTables" -s ./src/WebApp.sln -c ApplicationDbContext --msbuildprojectextensionspath obj/local
    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/WebApp.sln