name: .NET-Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET v5.0.201
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.201
    - name: Restore dependencies
      run: dotnet restore ./src/WebApp/WebApp.sln
    - name: Build
      run: dotnet build --no-restore ./src/WebApp/WebApp.sln
#    - name: Remove migrations 
#      run: Remove-Item -path ./src/WebApp/WebApp/Data/Migrations -WhatIf
#    - name: Create new migrations
#      run: dotnet ef migrations add "CreatedNewTables" -s ./src/WebApp/WebApp.sln -c ApplicationDbContext
    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/WebApp/WebApp.sln
